// <auto-generated />
using System;
using FASE_II_DAS_Gestion_de_expedientes_CRUD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FASE_II_DAS_Gestion_de_expedientes_CRUD.Migrations
{
    [DbContext(typeof(GestionexpedienteContext))]
    [Migration("20251107043824_CascadeDeleteAlumno")]
    partial class CascadeDeleteAlumno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FASE_II_DAS_Gestion_de_expedientes_CRUD.Models.Alumno", b =>
                {
                    b.Property<int>("AlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AlumnoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumnoId"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Grado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AlumnoId")
                        .HasName("PK__Alumno__90A6AA33D2C83993");

                    b.ToTable("Alumno", (string)null);
                });

            modelBuilder.Entity("FASE_II_DAS_Gestion_de_expedientes_CRUD.Models.Expediente", b =>
                {
                    b.Property<int>("ExpedienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExpedienteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpedienteId"));

                    b.Property<int?>("AlumnoId")
                        .HasColumnType("int")
                        .HasColumnName("AlumnoID");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<double?>("NotaFinal")
                        .HasColumnType("float");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ExpedienteId")
                        .HasName("PK__Expedien__EBC60A569E6C1148");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Expediente", (string)null);
                });

            modelBuilder.Entity("FASE_II_DAS_Gestion_de_expedientes_CRUD.Models.Materium", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("Docente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreMateria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaterialId")
                        .HasName("PK__Materia__C50613179779BFA2");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("FASE_II_DAS_Gestion_de_expedientes_CRUD.Models.Expediente", b =>
                {
                    b.HasOne("FASE_II_DAS_Gestion_de_expedientes_CRUD.Models.Alumno", "Alumno")
                        .WithMany("Expedientes")
                        .HasForeignKey("AlumnoId")
                        .HasConstraintName("FK__Expedient__Alumn__3E52440B");

                    b.HasOne("FASE_II_DAS_Gestion_de_expedientes_CRUD.Models.Materium", "Material")
                        .WithMany("Expedientes")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Expedient__Mater__3F466844");

                    b.Navigation("Alumno");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("FASE_II_DAS_Gestion_de_expedientes_CRUD.Models.Alumno", b =>
                {
                    b.Navigation("Expedientes");
                });

            modelBuilder.Entity("FASE_II_DAS_Gestion_de_expedientes_CRUD.Models.Materium", b =>
                {
                    b.Navigation("Expedientes");
                });
#pragma warning restore 612, 618
        }
    }
}
